### ISSUE TITLE
Fire Flame Ghost Egg not appearing in inventory

### ISSUE THREAD

**Issue by Tmvant** [twimu/TwilightMU-S16#8]
Devil Square 2 has a mob that drops the Fire Flame Ghost Egg. When picked up, the game says: ''Item picked up", but nothing appears in inventory.
What I checked:
- The ItemBag definition for this exists
- It's supposed to function similairly as a RUUD Box or Mastery Box
- I can't find any restrictions for it appearing anywhere

Item definition is:
`<Item Index="221" Name="Fire Flame Ghost Egg" Slot="-1" SkillIndex="0" Width="1" Height="1" Serial="1" Option="0" Drop="0" DropLevel="0" ReqLevel="0" Durability="1" IceRes="0" PoisonRes="0" LightRes="0" FireRes="0" EarthRes="0" WindRes="0" WaterRes="0" SetAttrib="0" DarkWizard="1" DarkKnight="1" FairyElf="1" MagicGladiator="1" DarkLord="1" Summoner="1" RageFighter="1" GrowLancer="1" RuneWizard="1" Slayer="1" GunCrusher="1" Type="0" Dump="0" Transaction="0" PersonalStore="0" StoreWarehouse="0" SellToNPC="0" ExpensiveItem="0" Repair="0" KindA="11" KindB="72" Overlap="0" NonValue="0" MasteryGrade="0" ModelPath="Data\Item\" ModelFile="PetEgg.bmd" />`

My only remaining solution is that the model is somehow non-existant or something.

**Comment by spanakis** [comment]
Check the event inventory
